-- load lsp installer first
require('configs.lsp')
require('configs.nvimtree')
require('configs.theme')
require('configs.telescope')
require('configs.treesitter')
require('configs.autopairs')
require('configs.surround')
require('configs.hlarg')
require('configs.bufferline')
require('configs.cursorline')
require('configs.comment')
require('configs.sittercontext')
require('configs.number')
require('configs.ufoconfig')
require('configs.dap')
